apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: pensjon-deployment-audit
  namespace: pensjon-revisjon
  labels:
    team: pensjon-revisjon
spec:
  image: {{ image }}
  port: 3000

  ingresses:
    - https://pensjon-deployment-audit.ansatt.nav.no

  liveness:
    path: /api/isalive
    port: 3000
    initialDelay: 20
    timeout: 60

  readiness:
    path: /api/isready
    port: 3000
    initialDelay: 20
    timeout: 60

  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 80

  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      memory: 4096Mi

  # Entra ID (Azure AD) authentication with login sidecar
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: 1e97cbc6-0687-4d23-aebd-c611035279c1  # pensjon-revisjon (admin)
          - id: 415d3817-c83d-44c9-a52b-5116757f8fa8  # teampensjon (user)
        extra:
          - "NAVident"
      replyURLs:
        - "http://localhost:3000/auth/callback"
    sidecar:
      enabled: true
      autoLogin: true

  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-f1-micro
        diskAutoresize: true
        databases:
          - name: pensjon-deployment-audit
            envVarPrefix: DB

  env:
    - name: NODE_ENV
      value: production
    - name: TZ
      value: Europe/Oslo
    - name: NAIS_GRAPHQL_URL
      value: https://console.nav.cloud.nais.io/graphql
    - name: ENABLE_PERIODIC_SYNC
      value: "true"
    - name: ALLOWED_ENVIRONMENTS
      value: "prod-fss,prod-gcp"

  envFrom:
    - secret: nais-deployment-audit

  accessPolicy:
    outbound:
      external:
        - host: api.github.com
        - host: console.nav.cloud.nais.io
        - host: slack.com
        - host: wss-primary.slack.com
        - host: wss-backup.slack.com
        - host: wss-mobile.slack.com
