import { index, layout, type RouteConfig, route } from '@react-router/dev/routes'

export default [
  route('api/isalive', 'routes/api/isalive.ts'),
  route('api/isready', 'routes/api/isready.ts'),
  route('api/reports/status', 'routes/api/reports.status.ts'),
  route('api/search', 'routes/api/search.ts'),
  route('api/users/search', 'routes/api/users.search.ts'),
  route('api/users/slack-lookup', 'routes/api/users.slack-lookup.ts'),
  route('api/checks/logs', 'routes/api/checks.logs.ts'),
  route('api/checks/annotations', 'routes/api/checks.annotations.ts'),
  route(
    'api/v1/apps/:team/:env/:app/verification-summary',
    'routes/api/v1.apps.$team.$env.$app.verification-summary.ts',
  ),
  route('api/v1/apps/:team/:env/:app/audit-reports', 'routes/api/v1.apps.$team.$env.$app.audit-reports.ts'),
  route(
    'api/v1/apps/:team/:env/:app/audit-reports/status',
    'routes/api/v1.apps.$team.$env.$app.audit-reports.status.ts',
  ),
  route(
    'api/v1/apps/:team/:env/:app/audit-reports/generate',
    'routes/api/v1.apps.$team.$env.$app.audit-reports.generate.ts',
  ),
  route(
    'api/v1/apps/:team/:env/:app/audit-reports/jobs/:jobId',
    'routes/api/v1.apps.$team.$env.$app.audit-reports.jobs.$jobId.ts',
  ),
  route(
    'api/v1/apps/:team/:env/:app/audit-reports/:reportId/download',
    'routes/api/v1.apps.$team.$env.$app.audit-reports.$reportId.download.ts',
  ),

  layout('routes/layout.tsx', [
    index('routes/home.tsx'),
    route('my-teams', 'routes/my-teams.tsx'),
    route('my-apps', 'routes/my-apps.tsx'),
    route('search', 'routes/search.tsx'),
    route('team/:team', 'routes/team/$team.tsx'),
    route('team/:team/env/:env', 'routes/team/$team.env.$env.tsx'),
    route('team/:team/env/:env/app/:app', 'routes/team/$team.env.$env.app.$app.tsx'),
    route('team/:team/env/:env/app/:app/admin', 'routes/team/$team.env.$env.app.$app.admin.tsx'),
    route('team/:team/env/:env/app/:app/slack', 'routes/team/$team.env.$env.app.$app.slack.tsx'),
    route(
      'team/:team/env/:env/app/:app/admin/verification-diff',
      'routes/team/$team.env.$env.app.$app.admin.verification-diff.tsx',
    ),
    route(
      'team/:team/env/:env/app/:app/admin/verification-diff/:deploymentId',
      'routes/team/$team.env.$env.app.$app.admin.verification-diff.$deploymentId.tsx',
    ),
    route(
      'team/:team/env/:env/app/:app/admin/status-history',
      'routes/team/$team.env.$env.app.$app.admin.status-history.tsx',
    ),
    route('team/:team/env/:env/app/:app/admin/sync-jobs', 'routes/team/$team.env.$env.app.$app.admin.sync-jobs.tsx'),
    route(
      'team/:team/env/:env/app/:app/admin/sync-job/:jobId',
      'routes/team/$team.env.$env.app.$app.admin.sync-job.$jobId.tsx',
    ),
    route('team/:team/env/:env/app/:app/deployments', 'routes/team/$team.env.$env.app.$app.deployments.tsx'),
    route(
      'team/:team/env/:env/app/:app/deployments/:deploymentId',
      'routes/team/$team.env.$env.app.$app.deployments.$deploymentId.tsx',
    ),
    route(
      'team/:team/env/:env/app/:app/deployments/:deploymentId/debug-verify',
      'routes/team/$team.env.$env.app.$app.deployments.$deploymentId.debug-verify.tsx',
    ),
    route(
      'team/:team/env/:env/app/:app/deployments/:deploymentId/debug-keywords',
      'routes/team/$team.env.$env.app.$app.deployments.$deploymentId.debug-keywords.tsx',
    ),
    route('deployments/verify', 'routes/deployments/verify.tsx'),
    route('deployments/:id', 'routes/deployments/$id.tsx'),
    route('users/:username', 'routes/users/$username.tsx'),
    route('admin', 'routes/admin/index.tsx'),
    route('admin/users', 'routes/admin/users.tsx'),
    route('admin/users/export', 'routes/admin/users.export.ts'),
    route('admin/sync-jobs', 'routes/admin/sync-jobs.tsx'),
    route('admin/sync-jobs/:jobId', 'routes/admin/sync-jobs.$jobId.tsx'),
    route('admin/audit-reports', 'routes/admin/audit-reports.tsx'),
    route('admin/audit-reports/:id/pdf', 'routes/admin/audit-reports.$id.pdf.ts'),
    route('admin/audit-reports/:id/xlsx', 'routes/admin/audit-reports.$id.xlsx.ts'),
    route('admin/audit-reports/:id/view', 'routes/admin/audit-reports.$id.view.ts'),
    route('admin/global-settings', 'routes/admin/global-settings.tsx'),
    route('admin/section-roles', 'routes/admin/section-roles.tsx'),
    route('admin/monorepos', 'routes/admin/monorepos.tsx'),
    route('admin/debug-repo-link-coverage', 'routes/admin/debug-repo-link-coverage.tsx'),
    route('admin/soft-deleted', 'routes/admin/soft-deleted.tsx'),
    route('admin/verification-diffs', 'routes/admin/verification-diffs.tsx'),
    route('admin/workflow-triggers', 'routes/admin/workflow-triggers.tsx'),
    route('admin/workflow-patterns', 'routes/admin/workflow-patterns.tsx'),
    route('admin/validate-monitored-apps', 'routes/admin/validate-monitored-apps.tsx'),
    route('admin/title-mismatches', 'routes/admin/title-mismatches-redirect.ts'),
    route('admin/data-mismatches', 'routes/admin/data-mismatches.tsx'),
    route('sections', 'routes/admin/sections.tsx'),
    route('sections/:slug/edit', 'routes/admin/sections.$slug.dev-teams.tsx'),
    route('sections/:sectionSlug/teams/:devTeamSlug', 'routes/sections.$sectionSlug.teams.$devTeamSlug.tsx'),
    route(
      'sections/:sectionSlug/teams/:devTeamSlug/admin',
      'routes/sections.$sectionSlug.teams.$devTeamSlug.admin.tsx',
    ),
    route(
      'sections/:sectionSlug/teams/:devTeamSlug/boards',
      'routes/sections.$sectionSlug.teams.$devTeamSlug.boards.tsx',
    ),
    route(
      'sections/:sectionSlug/teams/:devTeamSlug/dashboard',
      'routes/sections.$sectionSlug.teams.$devTeamSlug.dashboard.tsx',
    ),
    route(
      'sections/:sectionSlug/teams/:devTeamSlug/deployments',
      'routes/sections.$sectionSlug.teams.$devTeamSlug.deployments.tsx',
    ),
    route(
      'sections/:sectionSlug/teams/:devTeamSlug/:boardId',
      'routes/sections.$sectionSlug.teams.$devTeamSlug.$boardId.tsx',
    ),
    route('sections/:slug', 'routes/sections.$slug.tsx'),
    route('team/:team/env/:env/app/:app/admin/deviations', 'routes/team/$team.env.$env.app.$app.admin.deviations.tsx'),
  ]),
] satisfies RouteConfig
